# Generated by Django 2.2.2 on 2019-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('image', models.ImageField(default='media/images/image.jpg', upload_to='media/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
