# Generated by Django 2.2.2 on 2019-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='media/images/image.jpg', upload_to=''),
        ),
    ]
