# Generated by Django 3.0 on 2022-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220418_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default='static/media/default.jpg', upload_to='image/'),
        ),
    ]
