# Generated by Django 3.0 on 2022-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220418_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default='efault.jpg', upload_to=''),
        ),
    ]
